# Generated by Django 3.2.7 on 2021-09-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
